{
    parserClass="cz.cuni.mff.kyjovsm.robocop.parser.RobotFrameworkParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="RobotFramework"
    psiImplClassSuffix="Impl"
    psiPackage="cz.cuni.mff.kyjovsm.robocop.psi"
    psiImplPackage="cz.cuni.mff.kyjovsm.robocop.psi.impl"

    elementTypeHolderClass="cz.cuni.mff.kyjovsm.robocop.psi.RobotFrameworkTypes"
    elementTypeClass="cz.cuni.mff.kyjovsm.robocop.psi.RobotFrameworkElementType"
    tokenTypeClass="cz.cuni.mff.kyjovsm.robocop.psi.RobotFrameworkTokenType"

    psiImplUtilClass="cz.cuni.mff.kyjovsm.robocop.psi.impl.RobotFrameworkPsiImplUtil"
}

